### ISSUE TITLE
[C][0010] Create messaging page layout

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#10]
**Branch:**

- messaging-layout

**Component(s):**

- messages.component

**Service(s):**

- data.service

**Pull request(s):**

- [ ] Pull request for all functionality mentioned below

**Tasks:**
Create basic and simple layout for **Messaging component**. As a design example, use **friends dialogs page** of the Discord - your dialogs list is **on the left** in the form of the buttons list. Every button corresponds to the dialog you have. The list of dialogs is available in the **dialogs** object at **data.service** (use subscription example from **dashboard.component**).

- [x] Create Message input in the bottom of the page with a send button.
    - [x] It should be submitted by pressing send button or pressing enter key on the keyboard.
- [x] Use *ngFor to display messages. Display message text and sender name.
    - [x] Hardcode the list of messages as an array of message objects.
- [x] You should be able to switch between dialogs by pressing button with your friends name.
- [x] Create header for the dialog in the design of your desire.

**Angular material element(s):**

- MatCardModule
- MatButtonModule
- MatInputModule
- MatIconModule
https://material.angular.io/components/categories
