### ISSUE TITLE
[C][0011] Create basic friends list layout

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#11]
**Branch:**

- friends-layout

**Component(s):**

- friends.component

**Service(s):**

- data.service

**Pull request(s):**

- [ ] Pull request for all functionality mentioned below

**Tasks:**
Create basic and simple layout of the friends list. Either use cards layout or list layout. Make a side-bar with options "My Friends", "My Teachers" and "Search". Friends, teachers and search lists will be available at data.service.
First two options should contain a list of friends/teachers with regular options. Search should display search bar which will perform search.

- [x] Each friend is represented by a rectangle card or long list item.
- [x] Each card/list item should have an option of adding/removing friend, messaging friend, browsing friend's profile.
- [x] Hardcode online status.
- [x] Hardcode search function to search among hardcoded list. Display friend actions correspondingly.

**Angular material element(s):**

- MatCardModule
- MatButtonModule
- MatInputModule
- MatIconModule
https://material.angular.io/components/categories

**Comment by mdnahian** [comment]
For the search results should I assume I'm getting the entire list of users and then just filter based on the name? I don't see a search list in data.service so should I just make one there similar to the friends and teachers list

**Comment by chimZuk** [comment]
> For the search results should I assume I'm getting the entire list of users and then just filter based on the name? I don't see a search list in data.service so should I just make one there similar to the friends and teachers list

Oh, yes, just hardcode in the format you desire. We will go back to it after backend update 😉
