### ISSUE TITLE
[C][0012] Create basic tasks list layout

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#12]
**Component(s):**

- tasks.component

**Service(s):**

- data.service

**Pull request(s):**

- [ ] Pull request for all functionality mentioned below

**Tasks:**
Create basic and simple layout of the tasks list. Hardcoded tasks list is available at data.service.

- [ ] Create a navbar with options "Upcoming", "In Progress", "Completed" which correspond to the task's status property (0, 1, 2).
- [ ] Each task is represented by a rectangle card.
- [ ] Each card/list item should have an option of opening, sharing or deleting.
