### ISSUE TITLE
[C][0014] Create Tasks workspace

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#14]
**Branch:**

- workspace

**Component(s):**

- workspace.component

**Service(s):**

- data.service

**Pull request(s):**

- [ ] Pull request for all functionality mentioned below

**Tasks:**
Create basic workspace functionality using Canvas element and Konva.js library.

- [ ] Create a field with squares/lines background.
- [ ] Create onscreen keyboard with basic math symbols.
- [ ] Create cursor functionality.

**Angular material element(s):**

- N/A

**Library(s):**

- Konva.js
