### ISSUE TITLE
[C][0004] Create authorization logic

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#4]
**Component(s):**

- landing-page.component

**Service(s):**

- auth.service
- data.service

**Pull request(s):**

- [x] Pull request for changes mentioned below

**Tasks:**
Create login/registration form on the Landing page. Use MatCard element from Angular material library for form body, MatButton for buttons, MatFormField and MatInput for fields.

- [x] Create login/registration form
    - [x] Create necessary fields for login form
        - [x] Email
            - [x] Add validation - should be valid email
        - [x] Password
            - [x] Add validation - at least 4 characters
    - [x] Create necessary fields for registration form
        - [x] Name
        - [x] ~~Username~~
            - [x] ~~Add validation - at least 4 characters~~
        - [x] Email
            - [x] Add validation - should be valid email
        - [x] Password
            - [x] Add validation - at least 4 characters
    - [x] Create Login/Register button as well ass Go to Registration/Go to Login buttons
    - [x] Create corresponding API requests
        - [x] Use auth.service for API creation
    - [x] Create API for retrieving data from the server after login/registration
        - [x] Save that data in data.service
    - [x] Create displaying Authentication error
        - [x] Use MatSnackbar to display errors
