### ISSUE TITLE
[C][0005] Create dashboard layout

### ISSUE THREAD

**Issue by chimZuk** [scrawlless/client#5]
**Component(s):**

- dashboard.component

**Service(s):**

- data.service

**Pull request(s):**

- [ ] Pull request for all functionality mentioned below

**Tasks:**
Create basic and simple layout for Dashboard component with navigation buttons as well as profile popup. 

- [ ] Create expandable side navigation using MatSidenav
    - [ ] Create buttons for each of the following pages. It should contain Icon and the name of the page.
        - [ ] Tasks
        - [ ] Messages
        - [ ] Friends
- [ ] Create a toolbar with Scrawlless logo and profile button.
    - [ ] Profile button should open popup menu (use MatMenu) with user's name and following links/buttons
        - [ ] Settings (link)
        - [ ] Profile (link)
        - [ ] Log Out (button)
- [ ] Retrieve data from data.service to display user information
